%%%%%%%%%%%%%%%%%
%% Problem Two %%
%%%%%%%%%%%%%%%%%

% Each new term in the Fibonacci sequence is generated by adding the 
% previous two terms. By starting with 1 and 2, the first 10 terms will be:
%
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% By considering the terms in the Fibonacci sequence whose values do not 
% exceed four million, find the sum of the even-valued terms.

clear all;
%Using recursion to calculate the Fibonacci sequence  
A(1)=uint32(1), A(2)=uint32(1);
a=uint16(3);
while a<=100
    A(a)=A(a-1)+A(a-2);
    a=a+1;
end 

% determine the domain of A:do not exceed four million
A = A(find(A <= 4000000))

%mod is the function to calculate remainder
ans = sum(A(find((mod(A,2) == 1))))

%% Answer is 4613732